name = "pevensie"
version = "1.2.0"
description = "The backend application framework for Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "pevensie" }
links = [{ title = "Website", href = "https://pevensie.dev" }]
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
argus = ">= 1.0.2 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"
gtempo = ">= 7.2.2 and < 8.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
