name = "pevensie"
version = "0.1.0"
description = "The backend application framework for Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "pevensie" }
links = [{ title = "Website", href = "https://pevensie.dev" }]
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.51.0 and < 1.0.0"
gleam_erlang = ">= 0.30.0 and < 1.0.0"
argus = ">= 1.0.2 and < 2.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_crypto = ">= 1.4.0 and < 2.0.0"
gtempo = ">= 5.1.2 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
